# ~/.config/tmux-sessionizer/tmux-sessionizer.conf

TS_SESSION_COMMANDS=(
    "opencode ."
    "nvim ."
    "lazydocker"
    "bash -c 'mvn spring-boot:run; exec bash'"
    "bash -c 'mvn install; exec bash'"
)

TS_SEARCH_PATHS=(
    ~/
    ~/dotfiles
    ~/.config
    "/media/$USER/Int. Media/AlnixDev/Projects"
    "/media/$USER/Int. Media/Job"
    "$HOME/Desktop/Job"
    "/media/$USER/Archive/AlnixDev/vault-alnix404"
    "/media/$USER/Archive/AlnixDev/vault-alnixdev"
    "/media/$USER/Archive/Job/vault-university"
    "/media/$USER/Archive/Personal/vault-personal"
    "$HOME/Desktop/vault-desktop"
)
