# ~/.config/tmux-sessionizer/tmux-sessionizer.conf

TS_SESSION_COMMANDS=(
    "opencode ."
    "nvim ."
    "lazydocker"
    "mvn spring-boot:run; read"
    "mvn install; read"
)

# Add '....; read' to the end of commands that you want to keep the terminal open after execution.

TS_SEARCH_PATHS=(
    ~/
    ~/dotfiles
    ~/.config
    "/media/$USER/Int. Media/AlnixDev/Projects"
    "/media/$USER/Int. Media/Job"
    "$HOME/Desktop/Job"
    "/media/$USER/Archive/AlnixDev/vault-alnix404"
    "/media/$USER/Archive/AlnixDev/vault-alnixdev"
    "/media/$USER/Archive/Job/vault-university"
    "/media/$USER/Archive/Personal/vault-personal"
    "$HOME/Desktop/vault-desktop"
)
