Net/ThemeName "Yaru-dark"
Net/IconThemeName "Yaru"
Gtk/CursorThemeName "Yaru-dark"
Gtk/FontName "CaskaydiaMono NFM 11"
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Gtk/ApplicationPreferDarkTheme 1
