# Change prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Tmux colors
set -g default-terminal "tmux-256color"

# Basic status bar colors
set -g status-style bg=default

# Left side (Session name)
set -g status-left "#[fg=#7aa2f7,bold]  #S #[fg=#a9b1d6,nobold] "

# Window list colors
# Inactive window
setw -g window-status-style fg='#565f89',bg=default
setw -g window-status-format " #I:#W "

# Active window (Highlighted)
setw -g window-status-current-style fg='#ff9e64',bg='#24283b',bold
setw -g window-status-current-format " #[fg=#7aa2f7]#I#[fg=#a9b1d6]:#[fg=#ff9e64]#W "

# Right side (Date/Time)
set -g status-right "#[fg=#bb9af7] %Y-%m-%d #[fg=#7aa2f7] %H:%M "


# Start window numbering at 1
set -g base-index 1

# Start pane numbering at 1
setw -g pane-base-index 1

# Optional: Renumber windows automatically when one is closed
set -g renumber-windows on

# Kitty Graphics support
set -g allow-passthrough on
set -g visual-activity off

# Set the escape-time to 0 or a very low value (in milliseconds)
set -s escape-time 0

# Refresh tmux configuration
unbind r
bind r source-file ~/.tmux.conf

# Enable mouse support
set -g mouse on

# Vim keys for navigation between panes
bind -r ^ last-window
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Use vim keys in copy mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Fuzzy picker
bind-key -r f run-shell "tmux neww tmux-sessionizer"

# Direct project jumps
bind-key -r A run-shell "tmux-sessionizer '/media/$USER/Int. Media/AlnixDev/Projects'"
bind-key -r J run-shell "tmux-sessionizer '/media/$USER/Int. Media/Job'"
bind-key -r D run-shell "tmux-sessionizer '$HOME/Desktop/Job'"

# Direct vault jumps
bind-key -r V run-shell "tmux-sessionizer '/media/$USER/Archive/AlnixDev/vault-alnix404'"
bind-key -r B run-shell "tmux-sessionizer '/media/$USER/Archive/AlnixDev/vault-alnixdev'"
bind-key -r U run-shell "tmux-sessionizer '/media/$USER/Archive/Job/vault-university'"
bind-key -r P run-shell "tmux-sessionizer '/media/$USER/Archive/Personal/vault-personal'"
bind-key -r E run-shell "tmux-sessionizer '$HOME/Desktop/vault-desktop'"

# Direct session jumps(M means alt)
bind-key -r M-0 run-shell "tmux neww tmux-sessionizer -s 0"
bind-key -r M-1 run-shell "tmux neww tmux-sessionizer -s 1"
bind-key -r M-2 run-shell "tmux neww tmux-sessionizer -s 2"
bind-key -r M-3 run-shell "tmux neww tmux-sessionizer -s 3"
bind-key -r M-4 run-shell "tmux neww tmux-sessionizer -s 4"
bind-key -r M-5 run-shell "tmux neww tmux-sessionizer -s 5"
bind-key -r M-6 run-shell "tmux neww tmux-sessionizer -s 6"
