# Change prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Tmux colors
set -g default-terminal "tmux-256color"

# Basic status bar colors
set -g status-style bg=default

# Left side (Session name)
set -g status-left "#[fg=#7aa2f7,bold]  #S #[fg=#a9b1d6,nobold] "

# Window list colors
# Inactive window
setw -g window-status-style fg='#565f89',bg=default
setw -g window-status-format " #I:#W "

# Active window (Highlighted)
setw -g window-status-current-style fg='#ff9e64',bg='#24283b',bold
setw -g window-status-current-format " #[fg=#7aa2f7]#I#[fg=#a9b1d6]:#[fg=#ff9e64]#W "

# Right side (Date/Time)
set -g status-right "#[fg=#bb9af7] %Y-%m-%d #[fg=#7aa2f7] %H:%M "

# Vim keys for navigation between panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Start window numbering at 1
set -g base-index 1

# Start pane numbering at 1
setw -g pane-base-index 1

# Optional: Renumber windows automatically when one is closed
set -g renumber-windows on

# Kitty Graphics support
set -g allow-passthrough on
set -g visual-activity off

# Set the escape-time to 0 or a very low value (in milliseconds)
set -s escape-time 0

# Refresh tmux configuration
unbind r
bind r source-file ~/.tmux.conf

# Enable mouse support
set -g mouse on
