#!/bin/bash
# ~/.config/i3/assign-workspaces.sh

cm="eDP"      # central/laptop
lm="DP-1-0"   # left
rm="HDMI-A-0" # right

OUTPUT="$HOME/.config/i3/dynamic-workspaces.conf"

# Detect connected monitors
has_cm=$(xrandr --query | grep "^$cm connected" | wc -l)
has_lm=$(xrandr --query | grep "^$lm connected" | wc -l)
has_rm=$(xrandr --query | grep "^$rm connected" | wc -l)

# Pick the right layout script
if [ $has_lm -eq 1 ] && [ $has_rm -eq 1 ]; then
  ~/.screenlayout/layout-central-left-right.sh
elif [ $has_lm -eq 1 ]; then
  ~/.screenlayout/layout-central-left.sh
elif [ $has_rm -eq 1 ]; then
  ~/.screenlayout/layout-central-right.sh
else
  ~/.screenlayout/layout-central.sh
fi

# Fallback: send everything to cm if a monitor isn't present
lm_target=$([ $has_lm -eq 1 ] && echo "$lm" || echo "$cm")
rm_target=$([ $has_rm -eq 1 ] && echo "$rm" || echo "$cm")

# Start writing the file
cat >"$OUTPUT" <<EOF
# Auto-generated by assign-workspaces.sh — do not edit manually
EOF

# Define the groups: "Modifier | Output | Workspace Offset"
# Group 1: $mod (0 offset) -> cm (Workspaces 1-10)
# Group 2: Ctrl (9 offset) -> lm (Workspaces 11-20)
# Group 3: Mod1 (12 offset) -> rm (Workspaces 21-30)
groups=(
  "\$mod|$cm|0"
  "Ctrl|$lm_target|10"
  "\$alt|$rm_target|20"
)

for group in "${groups[@]}"; do
  # Split the group string into variables
  IFS="|" read -r mod target offset <<<"$group"

  echo -e "\n# --- Workspaces for $target (Mod: $mod) ---" >>"$OUTPUT"

  # Loop through numbers 1-9
  for i in {1..9}; do
    ws=$((i + offset))
    kb=$i

    # 1. Assign workspace to monitor
    echo "workspace \"$ws\" output $target" >>"$OUTPUT"

    # 2. Keybind to switch to workspace
    echo "bindsym $mod+$kb workspace $ws" >>"$OUTPUT"

    # 3. Keybind to move container to workspace
    echo "bindsym $mod+Shift+$kb move container to workspace $ws; workspace $ws" >>"$OUTPUT"

    echo "" >>"$OUTPUT"
  done

  ws_zero=$((offset + 10))
  echo "workspace \"$ws_zero\" output $target" >>"$OUTPUT"
  echo "bindsym $mod+0 workspace $ws_zero" >>"$OUTPUT"
  echo "bindsym $mod+Shift+0 move container to workspace $ws_zero; workspace $ws_zero" >>"$OUTPUT"
  echo "" >>"$OUTPUT"
done
